In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('moviesTMBD.csv')
print(df.head())
print(df.info())
print(df.describe())

   Unnamed: 0       id                     title  popularity  adult  \
0           0  1007757                   Swapped    327.5134  False
1           1      278  The Shawshank Redemption     65.3308  False
2           2      238             The Godfather     47.2346  False
3           3   687163         Project Hail Mary    422.0199  False
4           4      240     The Godfather Part II     27.6763  False

  original_language                                           overview  \
0                en  A small woodland creature and a majestic bird,...
1                en  Imprisoned in the 1940s for the double murder ...
2                en  Spanning the years 1945 to 1955, a chronicle o...
3                en  Science teacher Ryland Grace wakes up on a spa...
4                en  In the continuing saga of the Corleone crime f...

  release_date  vote_average  vote_count
0   2026-05-01         8.987        1320
1   1994-09-23         8.721       30387
2   1972-03-14         8.686       22929
3   2026-03-15         8.621        3950
4   1974-12-20         8.571       13901
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9980 entries, 0 to 9979
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         9980 non-null   int64
 1   id                 9980 non-null   int64
 2   title              9980 non-null   object
 3   popularity         9980 non-null   float64
 4   adult              9980 non-null   bool
 5   original_language  9980 non-null   object
 6   overview           9978 non-null   object
 7   release_date       9978 non-null   object
 8   vote_average       9980 non-null   float64
 9   vote_count         9980 non-null   int64
dtypes: bool(1), float64(2), int64(3), object(4)
memory usage: 711.6+ KB
None
        Unnamed: 0            id   popularity  vote_average    vote_count
count  9980.000000  9.980000e+03  9980.000000   9980.000000   9980.000000
mean   4989.500000  2.322215e+05     4.690097      6.750276   2115.381263
std    2881.122177  3.087803e+05    11.973625      0.641034   3373.638027
min       0.000000  2.000000e+00     0.008600      5.500000    300.000000
25%    2494.750000  1.042775e+04     1.818600      6.249750    477.000000
50%    4989.500000  4.333150e+04     2.768400      6.716500    871.000000
75%    7484.250000  4.145662e+05     4.689025      7.216000   2125.000000
max    9979.000000  1.472638e+06   499.085700      8.987000  39782.000000

In [5]:
df=df.dropna(subset=["overview", "release_date"])
df.isnull().sum()

Unnamed: 0           0
id                   0
title                0
popularity           0
adult                0
original_language    0
overview             0
release_date         0
vote_average         0
vote_count           0
dtype: int64

In [7]:
df=df.drop_duplicates()
df.head(3)

,Unnamed: 0,id,title,popularity,adult,original_language,overview,release_date,vote_average,vote_count
0,0,1007757,Swapped,327.5134,False,en,"A small woodland creature and a majestic bird,...",2026-05-01,8.987,1320
1,1,278,The Shawshank Redemption,65.3308,False,en,Imprisoned in the 1940s for the double murder ...,1994-09-23,8.721,30387
2,2,238,The Godfather,47.2346,False,en,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,8.686,22929

In [9]:
df.columns

Index(['Unnamed: 0', 'id', 'title', 'popularity', 'adult', 'original_language',
       'overview', 'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [11]:
df["release_date"]=pd.to_datetime(df["release_date"])

Cleaned Data set

In [12]:
df.to_csv("Cleaned_moviesTMBD.csv", index=False)

In [13]:
top_movies=df[df["vote_count"]>500].sort_values(by="vote_average", ascending=False)
top_movies

,Unnamed: 0,id,title,popularity,adult,original_language,overview,release_date,vote_average,vote_count
0,0,1007757,Swapped,327.5134,False,en,"A small woodland creature and a majestic bird,...",2026-05-01,8.987,1320
1,1,278,The Shawshank Redemption,65.3308,False,en,Imprisoned in the 1940s for the double murder ...,1994-09-23,8.721,30387
2,2,238,The Godfather,47.2346,False,en,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,8.686,22929
3,3,687163,Project Hail Mary,422.0199,False,en,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,8.621,3950
6,6,389,12 Angry Men,22.8937,False,en,The defense and the prosecution have rested an...,1957-04-10,8.600,9977
...,...,...,...,...,...,...,...,...,...,...
9975,9975,399173,The Assignment,2.1132,False,en,Ace assassin Frank Kitchen is double crossed b...,2016-06-08,5.538,560
9979,9979,277355,Everly,2.0746,False,en,"After she betrays a powerful mob boss, a woman...",2015-02-26,5.536,584
9972,9972,9904,The Wild,4.8729,False,en,An adolescent lion is accidentally shipped fro...,2006-04-06,5.500,1129
9974,9974,13043,Camping,0.9096,False,fr,Plastic surgeon Michel Saint-Josse is on his w...,2006-04-26,5.500,893
9963,9963,83,Open Water,2.0059,False,en,Two divers are left out at sea without a boat....,2004-08-06,5.500,1129